//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace adart.repository
{
    using System;
    using System.Collections.Generic;
    
    public partial class Category
    {
        public Category()
        {
            this.Offers = new HashSet<Offer>();
        }
    
        public string ID { get; set; }
        public string Name { get; set; }
    
        public virtual ICollection<Offer> Offers { get; set; }
    }
}
